# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy the shared requirements.txt file and frontend code
# Copy and install only requirements first to leverage cache

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend/ /app/

# Install Python dependencies globally

# Expose Streamlit default port
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]